function Table_Col()
{
 r=document.getElementById("ch");
 row=r.value;
 cr=document.getElementById("col");
 col=cr.value;
 fg=document.getElementById("fg");
 bg=document.getElementById("bg");
 if(row=="1")
 {
 	if(bg.checked==true)
 	{
 		x=document.getElementById("r1");
 		x.style.backgroundColor=col;
 	}
 	if(fg.checked==true)
 	{
 		x=document.getElementById("r1");
 		x.style.color=col;
 	}
 }
 if(row=="2")
 {
 	if(bg.checked==true)
 	{
 		x=document.getElementById("r2");
 		x.style.backgroundColor=col;
 	}
 	if(fg.checked==true)
 	{
 		x=document.getElementById("r2");
 		x.style.color=col;
 	}
 }
 if(row=="3")
 {
 	if(bg.checked==true)
 	{
 		x=document.getElementById("r3");
 		x.style.backgroundColor=col;
 	}
 	if(fg.checked==true)
 	{
 		x=document.getElementById("r3");
 		x.style.color=col;
 	}
 }
 
}
