# Generated by Django 4.1.2 on 2023-02-20 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_Log', '0002_pg_students_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg_students_attendance',
            name='Student_Regno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance_Log.student_details_pg', to_field='Regno'),
        ),
    ]
